---
name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yaml

  trigger-rendering:
    name: Trigger Rendering
    runs-on: ubuntu-24.04
    steps:
      - name: Trigger Rendering
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.TEMPLATES_RENDER_GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'coreeng',
              repo: 'core-platform-reference-applications',
              workflow_id: 'render-templates.yaml',
              ref: 'main'
            })
